### ISSUE TITLE
Submit it to Packagist

### ISSUE THREAD

**Issue by VincentMarmiesse** [cap340/M2DeletedProductImage#12]
Hi,

I just submitted your module to [Packagist](https://packagist.org/packages/cap/cleanmedia) so it's available via Composer, do you want to do it yourself so it's related to your account?

Thanks for your work :)

**Comment by cap340** [comment]
Hi,

I do not think it's very important that this package is associated with my account, as long as anybody can install it.

Thanks for your help.
